# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/widget_checking_row.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget_Checking_Row(object):
    def setupUi(self, Widget_Checking_Row):
        Widget_Checking_Row.setObjectName("Widget_Checking_Row")
        Widget_Checking_Row.resize(361, 198)
        Widget_Checking_Row.setStyleSheet("#frame {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #ffffff;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Widget_Checking_Row)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Widget_Checking_Row)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_date = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_date.sizePolicy().hasHeightForWidth())
        self.widget_date.setSizePolicy(sizePolicy)
        self.widget_date.setObjectName("widget_date")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_date)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addWidget(self.widget_date)
        self.widget_list = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_list.sizePolicy().hasHeightForWidth())
        self.widget_list.setSizePolicy(sizePolicy)
        self.widget_list.setObjectName("widget_list")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_list)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addWidget(self.widget_list)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Widget_Checking_Row)
        QtCore.QMetaObject.connectSlotsByName(Widget_Checking_Row)

    def retranslateUi(self, Widget_Checking_Row):
        _translate = QtCore.QCoreApplication.translate
        Widget_Checking_Row.setWindowTitle(_translate("Widget_Checking_Row", "Form"))
