# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/Dialog_Join.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog_Join(object):
    def setupUi(self, Dialog_Join):
        Dialog_Join.setObjectName("Dialog_Join")
        Dialog_Join.resize(425, 552)
        Dialog_Join.setStyleSheet("#label_title{\n"
"    font: 75 14pt \"맑은 고딕\";\n"
"}\n"
"\n"
"#widget_login_form{\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"#label_guide{\n"
"    color: #4A86E8;\n"
"    font: bold 10pt;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #DFDFDF;\n"
"    border-radius: 20px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #9FC5E8;\n"
"    border: 2px solid #C9DAF8;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #4A86E8;\n"
"    border: 2px solid #86AEEF;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Join)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_login_form = QtWidgets.QWidget(Dialog_Join)
        self.widget_login_form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_login_form.setObjectName("widget_login_form")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_login_form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget_login_form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.label_title = QtWidgets.QLabel(self.widget_2)
        self.label_title.setMinimumSize(QtCore.QSize(0, 30))
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_4.addWidget(self.label_title)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit_username = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_username.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout_6.addWidget(self.lineEdit_username)
        self.btn_valid_username = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_valid_username.sizePolicy().hasHeightForWidth())
        self.btn_valid_username.setSizePolicy(sizePolicy)
        self.btn_valid_username.setMinimumSize(QtCore.QSize(60, 30))
        self.btn_valid_username.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_valid_username.setObjectName("btn_valid_username")
        self.horizontalLayout_6.addWidget(self.btn_valid_username)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_password.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_5.addWidget(self.lineEdit_password)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.widget_10 = QtWidgets.QWidget(self.widget_2)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.widget_10)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEdit_name = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_name.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_name.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_8.addWidget(self.lineEdit_name)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_4.addWidget(self.widget_10)
        self.widget_9 = QtWidgets.QWidget(self.widget_2)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.widget_9)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lineEdit_email = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_email.setMinimumSize(QtCore.QSize(190, 0))
        self.lineEdit_email.setMaximumSize(QtCore.QSize(190, 16777215))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.horizontalLayout_7.addWidget(self.lineEdit_email)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_4.addWidget(self.widget_9)
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.widget_6)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_guide = QtWidgets.QLabel(self.widget)
        self.label_guide.setAlignment(QtCore.Qt.AlignCenter)
        self.label_guide.setObjectName("label_guide")
        self.verticalLayout_2.addWidget(self.label_guide)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.widget_6)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.btn_rules = QtWidgets.QPushButton(self.widget_3)
        self.btn_rules.setMinimumSize(QtCore.QSize(70, 30))
        self.btn_rules.setMaximumSize(QtCore.QSize(70, 16777215))
        self.btn_rules.setObjectName("btn_rules")
        self.horizontalLayout.addWidget(self.btn_rules)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.checkBox = QtWidgets.QCheckBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_8 = QtWidgets.QWidget(self.widget_6)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.btn_join = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_join.sizePolicy().hasHeightForWidth())
        self.btn_join.setSizePolicy(sizePolicy)
        self.btn_join.setObjectName("btn_join")
        self.horizontalLayout_4.addWidget(self.btn_join)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.verticalLayout_4.addWidget(self.widget_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget_login_form)

        self.retranslateUi(Dialog_Join)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Join)

    def retranslateUi(self, Dialog_Join):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Join.setWindowTitle(_translate("Dialog_Join", "회원가입"))
        self.label_title.setText(_translate("Dialog_Join", "WD 회원가입 페이지"))
        self.label_3.setText(_translate("Dialog_Join", "아이디"))
        self.btn_valid_username.setText(_translate("Dialog_Join", "중복확인"))
        self.label_4.setText(_translate("Dialog_Join", "비밀번호"))
        self.label_6.setText(_translate("Dialog_Join", "이름"))
        self.label_5.setText(_translate("Dialog_Join", "이메일"))
        self.label_guide.setText(_translate("Dialog_Join", "안내 문구"))
        self.label_7.setText(_translate("Dialog_Join", "WD 이용약관"))
        self.btn_rules.setText(_translate("Dialog_Join", "읽기"))
        self.label_2.setText(_translate("Dialog_Join", "확인했습니다."))
        self.btn_join.setText(_translate("Dialog_Join", "회원가입하기"))
