# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/detected_medi_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget_Detected_Item(object):
    def setupUi(self, Widget_Detected_Item):
        Widget_Detected_Item.setObjectName("Widget_Detected_Item")
        Widget_Detected_Item.resize(295, 68)
        Widget_Detected_Item.setStyleSheet("#widget{\n"
"    background-color: #ffffff;\n"
"    border-top: 2px solid #BABCBC;\n"
"    border-bottom: 2px solid #BABCBC;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget_Detected_Item)
        self.horizontalLayout.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Widget_Detected_Item)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_medi_name = QtWidgets.QLabel(self.widget)
        self.label_medi_name.setObjectName("label_medi_name")
        self.horizontalLayout_2.addWidget(self.label_medi_name)
        spacerItem = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(self.widget)
        self.btn_save.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon)
        self.btn_save.setIconSize(QtCore.QSize(24, 24))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.btn_delete = QtWidgets.QPushButton(self.widget)
        self.btn_delete.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/trash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon1)
        self.btn_delete.setIconSize(QtCore.QSize(24, 24))
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_2.addWidget(self.btn_delete)
        self.horizontalLayout.addWidget(self.widget)
        self.actionMedi_Item = QtWidgets.QAction(Widget_Detected_Item)
        self.actionMedi_Item.setObjectName("actionMedi_Item")

        self.retranslateUi(Widget_Detected_Item)
        QtCore.QMetaObject.connectSlotsByName(Widget_Detected_Item)

    def retranslateUi(self, Widget_Detected_Item):
        _translate = QtCore.QCoreApplication.translate
        Widget_Detected_Item.setWindowTitle(_translate("Widget_Detected_Item", "Form"))
        self.label_medi_name.setText(_translate("Widget_Detected_Item", "타이레놀 서방정 850mg"))
        self.actionMedi_Item.setText(_translate("Widget_Detected_Item", "Medi_Item"))
