# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/form_loader.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Loader(object):
    def setupUi(self, Form_Loader):
        Form_Loader.setObjectName("Form_Loader")
        Form_Loader.setWindowModality(QtCore.Qt.NonModal)
        Form_Loader.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_Loader.sizePolicy().hasHeightForWidth())
        Form_Loader.setSizePolicy(sizePolicy)
        Form_Loader.setStyleSheet("#widget_back{\n"
"    background-color : #ffffff;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_Loader)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_back = QtWidgets.QWidget(Form_Loader)
        self.widget_back.setObjectName("widget_back")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_back)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_back)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/image/pill_loader.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget_back)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.widget_back)

        self.retranslateUi(Form_Loader)
        QtCore.QMetaObject.connectSlotsByName(Form_Loader)

    def retranslateUi(self, Form_Loader):
        _translate = QtCore.QCoreApplication.translate
        Form_Loader.setWindowTitle(_translate("Form_Loader", "Form"))
        self.label_2.setText(_translate("Form_Loader", "화면 구성 중...."))
