# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/Form_Saved_Medi_List.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Saved_Medi_List(object):
    def setupUi(self, Form_Saved_Medi_List):
        Form_Saved_Medi_List.setObjectName("Form_Saved_Medi_List")
        Form_Saved_Medi_List.resize(950, 800)

        self.retranslateUi(Form_Saved_Medi_List)
        QtCore.QMetaObject.connectSlotsByName(Form_Saved_Medi_List)

    def retranslateUi(self, Form_Saved_Medi_List):
        _translate = QtCore.QCoreApplication.translate
        Form_Saved_Medi_List.setWindowTitle(_translate("Form_Saved_Medi_List", "Form"))
