# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/widget_schedule_row.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget_Schedule_Row(object):
    def setupUi(self, Widget_Schedule_Row):
        Widget_Schedule_Row.setObjectName("Widget_Schedule_Row")
        Widget_Schedule_Row.resize(536, 58)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget_Schedule_Row)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Widget_Schedule_Row)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_4.addWidget(self.label_21)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        spacerItem1 = QtWidgets.QSpacerItem(132, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Widget_Schedule_Row)
        QtCore.QMetaObject.connectSlotsByName(Widget_Schedule_Row)

    def retranslateUi(self, Widget_Schedule_Row):
        _translate = QtCore.QCoreApplication.translate
        Widget_Schedule_Row.setWindowTitle(_translate("Widget_Schedule_Row", "Form"))
        self.label_13.setText(_translate("Widget_Schedule_Row", "2023-08-27"))
        self.label_7.setText(_translate("Widget_Schedule_Row", "1회차"))
        self.label_14.setText(_translate("Widget_Schedule_Row", "오전 07:00"))
        self.label_19.setText(_translate("Widget_Schedule_Row", "2회차"))
        self.label_15.setText(_translate("Widget_Schedule_Row", "오후 01:00"))
        self.label_20.setText(_translate("Widget_Schedule_Row", "3회차"))
        self.label_16.setText(_translate("Widget_Schedule_Row", "오후 6:00"))
        self.label_21.setText(_translate("Widget_Schedule_Row", "4회차"))
        self.label_17.setText(_translate("Widget_Schedule_Row", "오후 9:00"))
